Doxygen: ConfigList Class Reference
ConfigList Class Reference
Class representing a list type option.
#include <configimpl.h>
Public Types
enum WidgetType {
String , File , Dir , FileAndDir ,
Enum
}
Public Types inherited from ConfigOption
enum OptionType {
O_Info , O_List , O_Enum , O_String ,
O_Int , O_Bool , O_Obsolete , O_Disabled
}
enum { MAX_OPTION_LENGTH = 23 }
Public Member Functions
ConfigList (const char *name, const char *doc)
void addValue (const char *v)
void addListEnumValue (const char *v)
void setWidgetType (WidgetType w)
WidgetType widgetType () const
StringVector * valueRef ()
StringVector getDefault ()
void emptyValueToDefault ()
void writeTemplate (TextStream &t, bool sl, bool)
void compareDoxyfile (TextStream &t, Config::CompareMode compareMode)
void writeXMLDoxyfile (TextStream &t)
void substEnvVars ()
void convertStrToVal (Config::CompareMode compareMode)
void init ()
bool isDefault ()
Public Member Functions inherited from ConfigOption
ConfigOption (OptionType t)
virtual ~ConfigOption ()
OptionType kind () const
QCString name () const
QCString docs () const
QCString dependsOn () const
void addDependency (const char *dep)
void setEncoding (const QCString &e)
void setUserComment (const QCString &u)
Private Attributes
std::vector< QCString > m_valueRange
StringVector m_value
StringVector m_defaultValue
WidgetType m_widgetType
Additional Inherited Members
Protected Member Functions inherited from ConfigOption
virtual void writeTemplate (TextStream &t, bool sl, bool upd)=0
virtual void compareDoxyfile (TextStream &t, Config::CompareMode compareMode)=0
virtual void writeXMLDoxyfile (TextStream &t)=0
virtual void convertStrToVal (Config::CompareMode)
virtual void emptyValueToDefault ()
virtual void substEnvVars ()=0
virtual void init ()
virtual bool isDefault ()
void writeBoolValue (TextStream &t, bool v, bool initSpace=true)
void writeIntValue (TextStream &t, int i, bool initSpace=true)
void writeStringValue (TextStream &t, const QCString &s, bool initSpace=true, bool wasQuoted=false)
void writeStringList (TextStream &t, const StringVector &l)
Protected Attributes inherited from ConfigOption
QCString m_spaces
QCString m_name
QCString m_doc
QCString m_dependency
QCString m_encoding
QCString m_userComment
OptionType m_kind
Detailed Description
Class representing a list type option.
Definition at line 122 of file configimpl.h.
Member Enumeration Documentation
WidgetType
enum ConfigList::WidgetType
Enumerator
String
File
Dir
FileAndDir
Enum
Definition at line 125 of file configimpl.h.
{ String, File, Dir, FileAndDir, Enum };
Constructor & Destructor Documentation
ConfigList()
ConfigList::ConfigList (const char * name, const char * doc) inline
Definition at line 126 of file configimpl.h.
      : ConfigOption(O_List)
    {
      m_name = name;
      m_doc = doc;
      m_widgetType = String;
    }
References ConfigOption::m_doc, ConfigOption::m_name, m_widgetType, ConfigOption::name(), and String.
Member Function Documentation
addListEnumValue()
void ConfigList::addListEnumValue (const char * v) inline
Definition at line 134 of file configimpl.h.
{ m_valueRange.push_back(v); }
References m_valueRange.
addValue()
void ConfigList::addValue (const char * v) inline
Definition at line 133 of file configimpl.h.
{ m_defaultValue.push_back(v); }
References m_defaultValue.
compareDoxyfile()
void ConfigList::compareDoxyfile (TextStream & t, Config::CompareMode compareMode) virtual
Implements ConfigOption.
Definition at line 476 of file configimpl.l.
{
  if (!isDefault()) writeTemplate(t,TRUE,TRUE);
}
References isDefault(), TRUE, and writeTemplate().
convertStrToVal()
void ConfigList::convertStrToVal (Config::CompareMode compareMode) virtual
Reimplemented from ConfigOption.
Definition at line 298 of file configimpl.l.
{
  if (m_widgetType != Enum) return;
  if (compareMode == Config::CompareMode::CompressedNoEnv)
  {
    for (const auto &p : m_value)
    {
      QCString s=p.c_str();
      if (containsEnvVar(s)) return;
    }
  }
  m_defaultValue.clear();
  for (const auto &p : m_value)
  {
    QCString val=p.c_str();
    val = val.stripWhiteSpace().lower();
    bool found = false;
    for (const auto &s : m_valueRange)
    {
      if (s.lower() == val)
      {
        for (const auto &d : m_defaultValue)
        {
          if (d == val.data())
          {
            found = true;
            break;
          }
        }
        if (!found) m_defaultValue.push_back(val.data());
        found = true;
        break;
      }
    }
    if (!found)
    {
      config_warn("argument '%s' for option '%s' is not a valid list enum value, skipping it\n",
                  qPrint(p),qPrint(m_name));
    }
  }
  m_value = m_defaultValue;
  m_defaultValue.clear();
}
References Config::CompressedNoEnv, config_warn(), containsEnvVar(), QCString::data(), Enum, found, QCString::lower(), m_defaultValue, ConfigOption::m_name, m_value, m_valueRange, m_widgetType, qPrint(), and QCString::stripWhiteSpace().
emptyValueToDefault()
void ConfigList::emptyValueToDefault () inline virtual
Reimplemented from ConfigOption.
Definition at line 139 of file configimpl.h.
{ if (m_value.empty() && !m_defaultValue.empty()) m_value=m_defaultValue; };
References m_defaultValue, and m_value.
getDefault()
StringVector ConfigList::getDefault () inline
Definition at line 138 of file configimpl.h.
{ return m_defaultValue; }
References m_defaultValue.
init()
void ConfigList::init () inline virtual
Reimplemented from ConfigOption.
Definition at line 145 of file configimpl.h.
{ m_value = m_defaultValue; }
References m_defaultValue, and m_value.
isDefault()
bool ConfigList::isDefault () virtual
Reimplemented from ConfigOption.
Definition at line 444 of file configimpl.l.
{
  auto get_stripped = [](std::string s)             { return QCString(s.c_str()).stripWhiteSpace(); };
  auto is_not_empty = [get_stripped](std::string s) { return !get_stripped(s).isEmpty();            };
  size_t defCnt = std::count_if(       m_value.begin(),       m_value.end(),is_not_empty);
  size_t valCnt = std::count_if(m_defaultValue.begin(),m_defaultValue.end(),is_not_empty);
  if ( valCnt != defCnt)
  {
    return false;
  }
  auto it1 = m_value.begin();
  auto it2 = m_defaultValue.begin();
  while (it1!=m_value.end() && it2!=m_defaultValue.end())
  {
    // skip over empty values
    while (it1!=m_value.end() && !is_not_empty(*it1))
    {
      ++it1;
    }
    if (it1!=m_value.end()) // non-empty value
    {
      if (get_stripped(*it1) != get_stripped(*it2)) // not the default, write as difference
      {
        return false;
      }
      ++it1;
      ++it2;
    }
  }
  return true;
}
References QCString::isEmpty(), m_defaultValue, m_value, and QCString::stripWhiteSpace().
Referenced by compareDoxyfile(), and writeXMLDoxyfile().
setWidgetType()
void ConfigList::setWidgetType (WidgetType w) inline
Definition at line 135 of file configimpl.h.
{ m_widgetType = w; }
References m_widgetType.
substEnvVars()
void ConfigList::substEnvVars () virtual
Implements ConfigOption.
Definition at line 1526 of file configimpl.l.
{
  substEnvVarsInStrList(m_value);
}
References m_value, and substEnvVarsInStrList().
valueRef()
StringVector * ConfigList::valueRef () inline
Definition at line 137 of file configimpl.h.
{ return &m_value; }
References m_value.
widgetType()
WidgetType ConfigList::widgetType () const inline
Definition at line 136 of file configimpl.h.
{ return m_widgetType; }
References m_widgetType.
writeTemplate()
void ConfigList::writeTemplate (TextStream & t, bool sl, bool) virtual
Implements ConfigOption.
Definition at line 427 of file configimpl.l.
{
  if (!sl)
  {
    t << "\n";
    t << convertToComment(m_doc, m_userComment);
    t << "\n";
  }
  else if (!m_userComment.isEmpty())
  {
    t << convertToComment("", m_userComment);
  }
  t << m_name << m_spaces.left(MAX_OPTION_LENGTH-m_name.length()) << "=";
  writeStringList(t,m_value);
  t << "\n";
}
References convertToComment(), QCString::isEmpty(), QCString::left(), QCString::length(), ConfigOption::m_doc, ConfigOption::m_name, ConfigOption::m_spaces, ConfigOption::m_userComment, m_value, ConfigOption::MAX_OPTION_LENGTH, and ConfigOption::writeStringList().
Referenced by compareDoxyfile().
writeXMLDoxyfile()
void ConfigList::writeXMLDoxyfile (TextStream & t) virtual
Implements ConfigOption.
Definition at line 481 of file configimpl.l.
{
  t << "  <option  id='" << m_name << "'";
  t << " default='" << (isDefault() ? "yes" : "no") << "'";
  t << " type='stringlist'";
  t << ">";
  t << "\n";
  for (const auto &p : m_value)
  {
    QCString s=p.c_str();
    t << "    <value>";
    t << "<![CDATA[";
    writeStringValue(t,s,false);
    t << "]]>";
    t << "</value>\n";
  }
  t << "  </option>\n";
}
References isDefault(), ConfigOption::m_name, m_value, and ConfigOption::writeStringValue().
Member Data Documentation
m_defaultValue
StringVector ConfigList::m_defaultValue private
Definition at line 150 of file configimpl.h.
Referenced by addValue(), convertStrToVal(), emptyValueToDefault(), getDefault(), init(), and isDefault().
m_value
StringVector ConfigList::m_value private
Definition at line 149 of file configimpl.h.
Referenced by convertStrToVal(), emptyValueToDefault(), init(), isDefault(), substEnvVars(), valueRef(), writeTemplate(), and writeXMLDoxyfile().
m_valueRange
std::vector<QCString> ConfigList::m_valueRange private
Definition at line 148 of file configimpl.h.
Referenced by addListEnumValue(), and convertStrToVal().
m_widgetType
WidgetType ConfigList::m_widgetType private
Definition at line 151 of file configimpl.h.
Referenced by ConfigList(), convertStrToVal(), setWidgetType(), and widgetType().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/configimpl.h
/home/runner/work/doxygen/doxygen/src/configimpl.l