Doxygen: DocTitle Class Reference
DocTitle Class Reference
Node representing a simple section title.
#include <docnode.h>
Public Member Functions
DocTitle (DocParser *parser, DocNodeVariant *parent)
void parse (DocNodeVariant *)
void parseFromString (DocNodeVariant *, const QCString &title)
bool hasTitle () const
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
DocNode (const DocNode &)=delete
DocNode & operator= (const DocNode &)=delete
DocNode (DocNode &&)=default
DocNode & operator= (DocNode &&)=default
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing a simple section title.
Definition at line 573 of file docnode.h.
Constructor & Destructor Documentation
DocTitle()
DocTitle::DocTitle (DocParser * parser, DocNodeVariant * parent) inline
Definition at line 576 of file docnode.h.
: DocCompoundNode(parser,parent) {}
Member Function Documentation
hasTitle()
bool DocTitle::hasTitle () const inline
Definition at line 579 of file docnode.h.
{ return !children().empty(); }
References DocCompoundNode::children(), and GrowVector< T >::empty().
Referenced by DocbookDocVisitor::operator()().
parse()
void DocTitle::parse (DocNodeVariant * thisVariant)
Definition at line 2693 of file docnode.cpp.
{
  DBG(("DocTitle::parse() start\n"));
  auto ns = AutoNodeStack(parser(),thisVariant);
  parser()->tokenizer.setStateTitle();
  int tok;
  while ((tok=parser()->tokenizer.lex()))
  {
    if (tok == TK_HTMLTAG)
    {
      QCString tagName = parser()->context.token->name;
      HtmlAttribList tagHtmlAttribs = parser()->context.token->attribs;
      int tagId = Mappers::htmlTagMapper->map(tagName);
      if (parser()->context.token->emptyTag && !(tagId&XML_CmdMask) &&
          tagId!=HTML_UNKNOWN && tagId!=HTML_IMG && tagId!=HTML_BR && tagId!=HTML_HR && tagId!=HTML_P
          && tagId!=HTML_DIV && tagId!=HTML_SPAN)
      {
          warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"HTML tag ('<%s/>') may not use the 'empty tag' XHTML syntax.",
                     qPrint(tagName));
      }
      switch (tagId)
      {
        case HTML_BOLD:
          if (parser()->context.token->emptyTag) break;
          else if (!parser()->context.token->endTag) parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::Bold,tagName,&parser()->context.token->attribs);
          else parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::Bold,tagName);
          break;
        case HTML_S:
          if (parser()->context.token->emptyTag) break;
          else if (!parser()->context.token->endTag) parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::S,tagName,&parser()->context.token->attribs);
          else parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::S,tagName);
          break;
        case HTML_STRIKE:
          if (parser()->context.token->emptyTag) break;
          else if (!parser()->context.token->endTag) parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::Strike,tagName,&parser()->context.token->attribs);
          else parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::Strike,tagName);
          break;
        case HTML_DEL:
          if (parser()->context.token->emptyTag) break;
          else if (!parser()->context.token->endTag) parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::Del,tagName,&parser()->context.token->attribs);
          else parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::Del,tagName);
          break;
        case HTML_UNDERLINE:
          if (parser()->context.token->emptyTag) break;
          else if (!parser()->context.token->endTag) parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::Underline,tagName,&parser()->context.token->attribs);
          else parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::Underline,tagName);
          break;
        case HTML_INS:
          if (parser()->context.token->emptyTag) break;
          else if (!parser()->context.token->endTag) parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::Ins,tagName,&parser()->context.token->attribs);
          else parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::Ins,tagName);
          break;
        case HTML_CODE:
          if (parser()->context.token->emptyTag) break;
          if (/*getLanguageFromFileName(parser()->context.fileName)==SrcLangExt_CSharp ||*/ parser()->context.xmlComment)
              // for C# source or inside a <summary> or <remark> section we
             // treat <code> as an XML tag (so similar to @code)
          {
            warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"xml/html tag </%s> not allowed in title section when in XML mode", qPrint(tagName));
            children().append<DocWord>(parser(),thisVariant,"<"+tagName+">");
          }
          else // normal HTML markup
          {
            if (parser()->context.token->emptyTag) break;
            else if (!parser()->context.token->endTag) parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::Code,tagName,&parser()->context.token->attribs);
            else parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::Code,tagName);
          }
          break;
        case HTML_EMPHASIS:
          if (parser()->context.token->emptyTag) break;
          else if (!parser()->context.token->endTag) parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::Italic,tagName,&parser()->context.token->attribs);
          else parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::Italic,tagName);
          break;
        case HTML_DIV:
          if (parser()->context.token->emptyTag)
          {
            parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::Div,tagName,&parser()->context.token->attribs);
            parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::Div,tagName);
          }
          else if (!parser()->context.token->endTag) parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::Div,tagName,&parser()->context.token->attribs);
          else parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::Div,tagName);
          break;
        case HTML_SPAN:
          if (parser()->context.token->emptyTag)
          {
            parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::Span,tagName,&parser()->context.token->attribs);
            parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::Span,tagName);
          }
          else if (!parser()->context.token->endTag) parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::Div,tagName,&parser()->context.token->attribs);
          else parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::Div,tagName);
          break;
        case HTML_SUB:
          if (parser()->context.token->emptyTag) break;
          else if (!parser()->context.token->endTag) parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::Subscript,tagName,&parser()->context.token->attribs);
          else parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::Subscript,tagName);
          break;
        case HTML_SUP:
          if (parser()->context.token->emptyTag) break;
          else if (!parser()->context.token->endTag) parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::Superscript,tagName,&parser()->context.token->attribs);
          else parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::Superscript,tagName);
          break;
        case HTML_CENTER:
          if (parser()->context.token->emptyTag) break;
          else if (!parser()->context.token->endTag) parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::Center,tagName,&parser()->context.token->attribs);
          else parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::Center,tagName);
          break;
        case HTML_SMALL:
          if (parser()->context.token->emptyTag) break;
          else if (!parser()->context.token->endTag) parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::Small,tagName,&parser()->context.token->attribs);
          else parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::Small,tagName);
          break;
        case HTML_CITE:
          if (parser()->context.token->emptyTag) break;
          else if (!parser()->context.token->endTag) parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::Cite,tagName,&parser()->context.token->attribs);
          else parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::Cite,tagName);
          break;
        case HTML_BR:
          children().append<DocLineBreak>(parser(),thisVariant,parser()->context.token->attribs);
          break;
        case HTML_A:
          if (!parser()->context.token->endTag)
          {
            parser()->handleAHref(thisVariant,children(),parser()->context.token->attribs);
          }
          break;
        case XML_C:
          if (parser()->context.token->emptyTag) break;
          else if (!parser()->context.token->endTag) parser()->handleStyleEnter(thisVariant,children(),DocStyleChange::Code,tagName,&parser()->context.token->attribs);
          else parser()->handleStyleLeave(thisVariant,children(),DocStyleChange::Code,tagName);
          break;
        case HTML_UNKNOWN:
          {
            QCString errTag = tagName;
            if (!parser()->context.token->attribsStr.isEmpty())
            {
              errTag += " " + parser()->context.token->attribsStr;
            }
            if (parser()->context.token->emptyTag) errTag += " /";
            else if (parser()->context.token->endTag) errTag = "/" + errTag;
            warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unsupported xml/html tag <%s> found", qPrint(errTag));
            children().append<DocWord>(parser(),thisVariant,"<"+errTag+">");
          }
          break;
        default:
          {
            QCString errTag = tagName;
            if (!parser()->context.token->attribsStr.isEmpty())
            {
              errTag += " " + parser()->context.token->attribsStr;
            }
            if (parser()->context.token->emptyTag) errTag += " /";
            else if (parser()->context.token->endTag) errTag = "/" + errTag;
            warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unexpected xml/html tag <%s> found", qPrint(errTag));
            children().append<DocWord>(parser(),thisVariant,"</"+errTag+">");
          }
          break;
      }
    }
    else if (!parser()->defaultHandleToken(thisVariant,tok,children()))
    {
      parser()->errorHandleDefaultToken(thisVariant,tok,children(),"title section");
    }
  }
  parser()->tokenizer.setStatePara();
  parser()->handlePendingStyleCommands(thisVariant,children());
  DBG(("DocTitle::parse() end\n"));
}
References DocNodeList::append(), TokenInfo::attribs, TokenInfo::attribsStr, DocStyleChange::Bold, DocStyleChange::Center, DocCompoundNode::children(), DocStyleChange::Cite, DocStyleChange::Code, DocParser::context, DBG, DocParser::defaultHandleToken(), DocStyleChange::Del, DocStyleChange::Div, TokenInfo::emptyTag, TokenInfo::endTag, DocParser::errorHandleDefaultToken(), DocParser::handleAHref(), DocParser::handlePendingStyleCommands(), DocParser::handleStyleEnter(), DocParser::handleStyleLeave(), HTML_A, HTML_BOLD, HTML_BR, HTML_CENTER, HTML_CITE, HTML_CODE, HTML_DEL, HTML_DIV, HTML_EMPHASIS, HTML_HR, HTML_IMG, HTML_INS, HTML_P, HTML_S, HTML_SMALL, HTML_SPAN, HTML_STRIKE, HTML_SUB, HTML_SUP, HTML_UNDERLINE, HTML_UNKNOWN, Mappers::htmlTagMapper, DocStyleChange::Ins, QCString::isEmpty(), DocStyleChange::Italic, Mapper::map(), TokenInfo::name, DocNode::parser(), qPrint(), DocStyleChange::S, DocTokenizer::setStatePara(), DocTokenizer::setStateTitle(), DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::Strike, DocStyleChange::Subscript, DocStyleChange::Superscript, TK_HTMLTAG, DocParserContext::token, DocParser::tokenizer, DocStyleChange::Underline, warn_doc_error(), XML_C, and XML_CmdMask.
parseFromString()
void DocTitle::parseFromString (DocNodeVariant * thisVariant, const QCString & title)
Definition at line 2861 of file docnode.cpp.
{
  children().append<DocWord>(parser(),thisVariant,text);
}
References DocNodeList::append(), DocCompoundNode::children(), and DocNode::parser().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/docnode.h
/home/runner/work/doxygen/doxygen/src/docnode.cpp